from types import SimpleNamespace

HPS_BASIC = {
    'pong': SimpleNamespace(**{
        'env_name':             "PongNoFrameskip-v4",
        'stop_reward':          18.0,
        'max_steps':            2_000_000,
        'memory_capacity':      100_000,
        'memory_initial':       10_000,
        'target_sync':          1000,
        'train_frequency':      1,
        'epsilon_start':        1.0,
        'epsilon_end':          0.01,
        'epsilon_frames':       100_000,
        'learning_rate':        1e-4,
        'gamma':                0.99,
        'batch_size':           32,
        'net_type':             'conv',
        'save_frequency':       100,
        'frame_stack':          4,
        'unroll_steps':         2,
        'beta_start':           0.4,
        'beta_end':             1.0,
        'beta_frames':          100_000,
    }),

    'breakout': SimpleNamespace(**{
        'env_name':             "BreakoutNoFrameskip-v4",
        'stop_reward':          500.0,
        'max_steps':            5_000_000,
        'memory_capacity':      1_000_000,
        'memory_initial':       50_000,
        'target_sync':          10_000,
        'train_frequency':      1,
        'epsilon_start':        1.0,
        'epsilon_end':          0.1,
        'epsilon_frames':       1_000_000,
        'learning_rate':        2.5e-4,
        'gamma':                0.99,
        'batch_size':           32,
        'net_type':             'conv',
        'save_frequency':       100,
        'frame_stack':          4,
        'unroll_steps':         4,
        'beta_start':           0.4,
        'beta_end':             1.0,
        'beta_frames':          100_000,
    }),

    'invaders': SimpleNamespace(**{
        'env_name':             "SpaceInvadersNoFrameskip-v4",
        'stop_reward':          500.0,
        'max_steps':            5_000_000,
        'memory_capacity':      1_000_000,
        'memory_initial':       50_000,
        'target_sync':          10_000,
        'train_frequency':      1,
        'epsilon_start':        1.0,
        'epsilon_end':          0.1,
        'epsilon_frames':       1_000_000,
        'learning_rate':        2.5e-4,
        'gamma':                0.99,
        'batch_size':           32,
        'net_type':             'conv',
        'save_frequency':       100,
        'frame_stack':          4,
        'unroll_steps':         4,
        'beta_start':           0.4,
        'beta_end':             1.0,
        'beta_frames':          100_000,
    }),
}

HPS_RAINBOW = {
    'pong': SimpleNamespace(**{
        'env_name':             "PongNoFrameskip-v4",
        'stop_reward':          18.0,
        'max_steps':            10_000_000,
        'memory_capacity':      1_000_000,
        'memory_initial':       80_000,
        'target_sync':          32_000,
        'train_frequency':      4,
        'epsilon_start':        1.0,
        'epsilon_end':          0.01,
        'epsilon_frames':       100_000,
        'learning_rate':        6.25e-5,
        'gamma':                0.99,
        'batch_size':           32,
        'net_type':             'conv',
        'save_frequency':       100,
        'frame_stack':          4,
        'unroll_steps':         3,
        'beta_start':           0.4,
        'beta_end':             1.0,
        'beta_frames':          100_000,
    }),

    'breakout': SimpleNamespace(**{
        'env_name':             "BreakoutNoFrameskip-v4",
        'stop_reward':          18.0,
        'max_steps':            10_000_000,
        'memory_capacity':      1_000_000,
        'memory_initial':       80_000,
        'target_sync':          32_000,
        'train_frequency':      4,
        'epsilon_start':        1.0,
        'epsilon_end':          0.01,
        'epsilon_frames':       100_000,
        'learning_rate':        6.25e-5,
        'gamma':                0.99,
        'batch_size':           32,
        'net_type':             'conv',
        'save_frequency':       100,
        'frame_stack':          4,
        'unroll_steps':         3,
        'beta_start':           0.4,
        'beta_end':             1.0,
        'beta_frames':          100_000,
    }),

    'invaders': SimpleNamespace(**{
        'env_name':             "SpaceInvadersNoFrameskip-v4",
        'stop_reward':          18.0,
        'max_steps':            10_000_000,
        'memory_capacity':      1_000_000,
        'memory_initial':       80_000,
        'target_sync':          32_000,
        'train_frequency':      4,
        'epsilon_start':        1.0,
        'epsilon_end':          0.01,
        'epsilon_frames':       100_000,
        'learning_rate':        6.25e-5,
        'gamma':                0.99,
        'batch_size':           32,
        'net_type':             'conv',
        'save_frequency':       100,
        'frame_stack':          4,
        'unroll_steps':         3,
        'beta_start':           0.4,
        'beta_end':             1.0,
        'beta_frames':          100_000,
    }),
}
